import { ChecklistItem } from '@/types'

export const DEFAULT_CHECKLIST_ITEMS: ChecklistItem[] = [
  // ─── SEMANAL ────────────────────────────────────────────────────────────────
  {
    id: 'ck-s-1',
    title: 'Reunião de alinhamento semanal com sócio',
    frequency: 'semanal',
    category: 'reuniao_socio',
    order: 1,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-2',
    title: 'Weekly Review com o time (Marketing, Comercial, Operacional)',
    frequency: 'semanal',
    category: 'reuniao_time',
    order: 2,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-3',
    title: 'Check-in semanal com clientes ativos',
    frequency: 'semanal',
    category: 'reuniao_clientes',
    order: 3,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-4',
    title: 'Reuniões de prospecção com novos clientes (SDR)',
    frequency: 'semanal',
    category: 'reuniao_novos_clientes',
    order: 4,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-5',
    title: 'Review de métricas semanais (MRR, leads, conversão)',
    frequency: 'semanal',
    category: 'operacional',
    order: 5,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-6',
    title: 'Aprovação de conteúdo da semana (calendário editorial)',
    frequency: 'semanal',
    category: 'marketing',
    order: 6,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-7',
    title: 'Revisão do pipeline comercial',
    frequency: 'semanal',
    category: 'operacional',
    order: 7,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-s-8',
    title: 'Reunião com parceiros externos (quando agendada)',
    frequency: 'semanal',
    category: 'reuniao_parceiros',
    order: 8,
    created_at: '2026-03-01',
  },

  // ─── MENSAL ─────────────────────────────────────────────────────────────────
  {
    id: 'ck-m-1',
    title: 'Apresentação de resultados mensais para clientes',
    frequency: 'mensal',
    category: 'reuniao_clientes',
    order: 1,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-2',
    title: 'All Hands com todo o time',
    frequency: 'mensal',
    category: 'reuniao_time',
    order: 2,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-3',
    title: 'Revisão de metas mensais com sócio',
    frequency: 'mensal',
    category: 'reuniao_socio',
    order: 3,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-4',
    title: 'Reunião de revisão com parceiros estratégicos',
    frequency: 'mensal',
    category: 'reuniao_parceiros',
    order: 4,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-5',
    title: 'Análise financeira mensal (DRE, caixa, churn)',
    frequency: 'mensal',
    category: 'financeiro',
    order: 5,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-6',
    title: 'Revisão de BSC por departamento',
    frequency: 'mensal',
    category: 'estrategia',
    order: 6,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-7',
    title: 'Planejamento de conteúdo do próximo mês',
    frequency: 'mensal',
    category: 'marketing',
    order: 7,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-8',
    title: 'Reunião de follow-up com novos clientes em negociação',
    frequency: 'mensal',
    category: 'reuniao_novos_clientes',
    order: 8,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-m-9',
    title: 'Avaliação de NPS e satisfação dos clientes',
    frequency: 'mensal',
    category: 'operacional',
    order: 9,
    created_at: '2026-03-01',
  },

  // ─── TRIMESTRAL ─────────────────────────────────────────────────────────────
  {
    id: 'ck-t-1',
    title: 'Off-site executivo de revisão e planejamento (OKR)',
    frequency: 'trimestral',
    category: 'estrategia',
    order: 1,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-t-2',
    title: 'Apresentação de resultados trimestrais para clientes premium',
    frequency: 'trimestral',
    category: 'reuniao_clientes',
    order: 2,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-t-3',
    title: 'Revisão de OKRs e NCTs com time de liderança',
    frequency: 'trimestral',
    category: 'reuniao_time',
    order: 3,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-t-4',
    title: 'Revisão e renegociação de parcerias estratégicas',
    frequency: 'trimestral',
    category: 'reuniao_parceiros',
    order: 4,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-t-5',
    title: 'Revisão de posicionamento e proposta de valor',
    frequency: 'trimestral',
    category: 'marketing',
    order: 5,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-t-6',
    title: 'Revisão de portfólio de serviços e precificação',
    frequency: 'trimestral',
    category: 'estrategia',
    order: 6,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-t-7',
    title: 'Revisão financeira trimestral (projeções e caixa)',
    frequency: 'trimestral',
    category: 'financeiro',
    order: 7,
    created_at: '2026-03-01',
  },

  // ─── ANUAL ──────────────────────────────────────────────────────────────────
  {
    id: 'ck-a-1',
    title: 'Planejamento estratégico anual (visão, metas, OKRs)',
    frequency: 'anual',
    category: 'estrategia',
    order: 1,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-a-2',
    title: 'Revisão anual de resultados com clientes',
    frequency: 'anual',
    category: 'reuniao_clientes',
    order: 2,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-a-3',
    title: 'Avaliação de desempenho e desenvolvimento do time',
    frequency: 'anual',
    category: 'reuniao_time',
    order: 3,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-a-4',
    title: 'Revisão e renovação de parcerias estratégicas anuais',
    frequency: 'anual',
    category: 'reuniao_parceiros',
    order: 4,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-a-5',
    title: 'Revisão de posicionamento de marca e identidade',
    frequency: 'anual',
    category: 'marketing',
    order: 5,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-a-6',
    title: 'Revisão societária e alinhamento de longo prazo com sócio',
    frequency: 'anual',
    category: 'reuniao_socio',
    order: 6,
    created_at: '2026-03-01',
  },
  {
    id: 'ck-a-7',
    title: 'Fechamento fiscal e planejamento tributário',
    frequency: 'anual',
    category: 'financeiro',
    order: 7,
    created_at: '2026-03-01',
  },
]
